using UnityEngine;

namespace com.Settings
{
  [CreateAssetMenu(fileName = "LevelAutoGenerated", menuName = "Settings/Levels/AutoGenerated", order = 2)]
  public class LevelAutoGeneratedSettings : LevelSettingsBase
  {
    [Header("Properties for \nautomatic field generation")]
    [Space]
    [SerializeField]
    private Vector2Int _fieldSize = new Vector2Int(9, 9);
    [Range(1, 4)]
    [SerializeField]
    private int _gatesCount = 1;

    public Vector2Int FieldSize => _fieldSize;

    public int GatesCount => _gatesCount;
  }
}